package net.archasmiel.thaumcraft.init;

import net.archasmiel.thaumcraft.datagen.generation.ModItemGeneration;
import net.archasmiel.thaumcraft.datagen.generation.wandGeneration.Wand;
import net.minecraft.world.item.Item;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import net.archasmiel.thaumcraft.ThaumcraftMod;

import java.util.function.Supplier;

public class ModItemRegister {

    public static final DeferredRegister<Item> ITEMS
            = DeferredRegister.create(ForgeRegistries.ITEMS, ThaumcraftMod.MOD_ID);

    public static final RegistryObject<Item> ALUMENTUM = registerCommonItem("alumentum","item");
    public static final RegistryObject<Item> AMBER = registerCommonItem("amber","item");
    public static final RegistryObject<Item> BATH_SALTS = registerCommonItem("bath_salts","item");
    public static final RegistryObject<Item> BAUBLE_AMULET = registerCommonItem("bauble_amulet","item");
    public static final RegistryObject<Item> BAUBLE_BELT = registerCommonItem("bauble_belt","item");
    public static final RegistryObject<Item> BAUBLE_RING = registerCommonItem("bauble_ring","item");
    public static final RegistryObject<Item> BAUBLE_RING_IRON = registerCommonItem("bauble_ring_iron","item");
    public static final RegistryObject<Item> BOOTSTRAVELER = registerCommonItem("bootstraveler","item");
    public static final RegistryObject<Item> BOTTLE_TAINT = registerCommonItem("bottle_taint","item");
    public static final RegistryObject<Item> BRAIN = registerCommonItem("brain","item");
    public static final RegistryObject<Item> BUCKET_DEATH = registerCommonItem("bucket_death","item");
    public static final RegistryObject<Item> BUCKET_PURE = registerCommonItem("bucket_pure","item");
    public static final RegistryObject<Item> CHARM = registerCommonItem("charm","item");
    public static final RegistryObject<Item> BONEBOW = registerCommonItem("bonebow","item");
    public static final RegistryObject<Item> CLOTH = registerCommonItem("cloth","item");
    public static final RegistryObject<Item> CLOTHBOOTS = registerCommonItem("clothboots","item");
    public static final RegistryObject<Item> CLOTHBOOTSOVER = registerCommonItem("clothbootsover","item");
    public static final RegistryObject<Item> CLOTHCHEST = registerCommonItem("clothchest","item");
    public static final RegistryObject<Item> CLOTHCHEATOVER = registerCommonItem("clothchestover","item");
    public static final RegistryObject<Item> CLOTHLEGS = registerCommonItem("clothlegs","item");
    public static final RegistryObject<Item> CLOTHLEGSOVER = registerCommonItem("clothlegsover","item");
    public static final RegistryObject<Item> CLUSTERCINNABAR = registerCommonItem("clustercinnabar","item");
    public static final RegistryObject<Item> CLUSTERCOPPER = registerCommonItem("clustercopper","item");
    public static final RegistryObject<Item> CLUSTERGOLD = registerCommonItem("clustergold","item");
    public static final RegistryObject<Item> CLUSTERIRON = registerCommonItem("clusteriron","item");
    public static final RegistryObject<Item> CLUSTERLEAD = registerCommonItem("clusterlead","item");
    public static final RegistryObject<Item> CLUSTERSILVER = registerCommonItem("clustersilver","item");
    public static final RegistryObject<Item> CLUSTERTIN = registerCommonItem("clustertin","item");
    public static final RegistryObject<Item> COIN = registerCommonItem("coin","item");
    public static final RegistryObject<Item> CRIMSON_BLADE = registerCommonItem("crimson_blade","item");
    public static final RegistryObject<Item> CRIMSON_RITES = registerCommonItem("crimson_rites","item");
    public static final RegistryObject<Item> CRYSTALESSENCE = registerCommonItem("crystalessence","item");
    public static final RegistryObject<Item> CULTISTBOOTS = registerCommonItem("cultistboots","item");
    public static final RegistryObject<Item> CULTISTPLATECHEST = registerCommonItem("cultistplatechest","item");
    public static final RegistryObject<Item> CULTISTPLATEHELM = registerCommonItem("cultistplatehelm","item");
    public static final RegistryObject<Item> CULTISTPLATELEADERCHEST = registerCommonItem("cultistplateleaderchest","item");
    public static final RegistryObject<Item> CULTSTPLATELEADERHELM = registerCommonItem("cultistplateleaderhelm","item");
    public static final RegistryObject<Item> CULTISTPLATELEADERLEGS = registerCommonItem("cultistplateleaderlegs","item");
    public static final RegistryObject<Item> CULTISTPLATELEGS = registerCommonItem("cultistplatelegs","item");
    public static final RegistryObject<Item> CULTISTROBECHEST = registerCommonItem("cultistrobechest","item");
    public static final RegistryObject<Item> CULTISTROBEHELM = registerCommonItem("cultistrobehelm","item");
    public static final RegistryObject<Item> CULTISTROBELEGS = registerCommonItem("cultistrobelegs","item");
    public static final RegistryObject<Item> DISCOVERY = registerCommonItem("discovery","item");
    public static final RegistryObject<Item> DUST = registerCommonItem("dust","item");
    public static final RegistryObject<Item> EL_ARROW_AIR = registerCommonItem("el_arrow_air","item");
    public static final RegistryObject<Item> EL_ARROW_EATRH = registerCommonItem("el_arrow_earth","item");
    public static final RegistryObject<Item> EL_ARROW_ENTROPY = registerCommonItem("el_arrow_entropy","item");
    public static final RegistryObject<Item> EL_ARROW_FIRE = registerCommonItem("el_arrow_fire","item");
    public static final RegistryObject<Item> EL_ARROW_ORDER = registerCommonItem("el_arrow_order","item");
    public static final RegistryObject<Item> EL_ARROW_WATER = registerCommonItem("el_arrow_water","item");
    public static final RegistryObject<Item> ELDRITCH_OBJECT = registerCommonItem("eldritch_object","item");
    public static final RegistryObject<Item> ELDRITCH_OBJECT_2 = registerCommonItem("eldritch_object_2","item");
    public static final RegistryObject<Item> ELDRITCH_OBJECT_3 = registerCommonItem("eldritch_object_3","item");
    public static final RegistryObject<Item> ELEMENTALAXE = registerCommonItem("elementalaxe","item");
    public static final RegistryObject<Item> ELEMENTALHOE = registerCommonItem("elementalhoe","item");
    public static final RegistryObject<Item> ELEMENTALPICK = registerCommonItem("elementalpick","item");
    public static final RegistryObject<Item> ELEMENTALSHOVEL = registerCommonItem("elementalshovel","item");
    public static final RegistryObject<Item> ELEMENTALSWORD = registerCommonItem("elementalsword","item");
    public static final RegistryObject<Item> ESSENCE = registerCommonItem("essence","item");
    public static final RegistryObject<Item> FILTER = registerCommonItem("filter","item");
    public static final RegistryObject<Item> FOCUS = registerCommonItem("focus","item");
    public static final RegistryObject<Item> FOCUS_EXCAVATION = registerCommonItem("focus_excavation","item");
    public static final RegistryObject<Item> FOCUS_FIRE = registerCommonItem("focus_fire","item");
    public static final RegistryObject<Item> FOCUS_FROST = registerCommonItem("focus_frost","item");
    public static final RegistryObject<Item> FOCUS_HELLBAT = registerCommonItem("focus_hellbat","item");
    public static final RegistryObject<Item> FOCUS_HELLBAT_ORN = registerCommonItem("focus_hellbat_orn","item");
    public static final RegistryObject<Item> FOCUS_PECH = registerCommonItem("focus_pech","item");
    public static final RegistryObject<Item> FOCUS_PECH_DEPTH = registerCommonItem("focus_pech_depth","item");
    public static final RegistryObject<Item> FOCUS_PORTABLEHOLE = registerCommonItem("focus_portablehole","item");
    public static final RegistryObject<Item> FOCUS_PORTABLEHOLE_DEPTH = registerCommonItem("focus_portablehole_depth","item");
    public static final RegistryObject<Item> FOCUS_PRIMAL = registerCommonItem("focus_primal","item");
    public static final RegistryObject<Item> FOCUS_PRIMAL_DEPTH = registerCommonItem("focus_primal_depth","item");
    public static final RegistryObject<Item> FOCUS_REVERSAL = registerCommonItem("focus_reversal","item");
    public static final RegistryObject<Item> FOCUS_SHOCK = registerCommonItem("focus_shock","item");
    public static final RegistryObject<Item> FOCUS_TRADE = registerCommonItem("focus_trade","item");
    public static final RegistryObject<Item> FOCUS_TRADE_ORN = registerCommonItem("focus_trade_orn","item");
    public static final RegistryObject<Item> FOCUS_WARDING = registerCommonItem("focus_warding","item");
    public static final RegistryObject<Item> FOCUS_WARDING_DEPTH = registerCommonItem("focus_warding_depth","item");
    public static final RegistryObject<Item> FOCUS_WARDING_ORN = registerCommonItem("focus_warding_orn","item");
    public static final RegistryObject<Item> FOCUS_WHATEVER_ORN = registerCommonItem("focus_whatever_orn","item");
    public static final RegistryObject<Item> FOCUS_POUCH = registerCommonItem("focus_pouch","item");
    public static final RegistryObject<Item> FOCUS_POUCH_BAUBLE = registerCommonItem("focus_pouch_bauble","item");
    public static final RegistryObject<Item> GOGGLESREVEALING = registerCommonItem("gogglesrevealing","item");
    public static final RegistryObject<Item> GOLEM_CLAY = registerCommonItem("golem_clay","item");
    public static final RegistryObject<Item> GOLEM_CORE_BLANK = registerCommonItem("golem_core_blank","item");
    public static final RegistryObject<Item> GOLEM_CORE_BODYGUARD = registerCommonItem("golem_core_bodyguard","item");
    public static final RegistryObject<Item> GOLEM_CORE_BUTCHER = registerCommonItem("golem_core_butcher","item");
    public static final RegistryObject<Item> GOLEM_CORE_EMPTY = registerCommonItem("golem_core_empty","item");
    public static final RegistryObject<Item> GOLEM_CORE_ESSENTIA = registerCommonItem("golem_core_essentia","item");
    public static final RegistryObject<Item> GOLEM_CORE_FILL = registerCommonItem("golem_core_fill","item");
    public static final RegistryObject<Item> GOLEM_CORE_FISH = registerCommonItem("golem_core_fish","item");
    public static final RegistryObject<Item> GOLEM_CORE_GATHER = registerCommonItem("golem_core_gather","item");
    public static final RegistryObject<Item> GOLEM_CORE_GUARD = registerCommonItem("golem_core_guard","item");
    public static final RegistryObject<Item> GOLEM_CORE_HARVEST = registerCommonItem("golem_core_harvest","item");
    public static final RegistryObject<Item> GOLEM_CORE_LIQUID = registerCommonItem("golem_core_liquid","item");
    public static final RegistryObject<Item> GOLEM_CORE_LUMBER = registerCommonItem("golem_core_lumber","item");
    public static final RegistryObject<Item> GOLEM_CORE_PATROL = registerCommonItem("golem_core_patrol","item");
    public static final RegistryObject<Item> GOLEM_CORE_SORTING = registerCommonItem("golem_core_sorting","item");
    public static final RegistryObject<Item> GOLEM_CORE_USE = registerCommonItem("golem_core_use","item");
    public static final RegistryObject<Item> GOLEM_FLESH = registerCommonItem("golem_flesh","item");
    public static final RegistryObject<Item> GOLEM_IRON = registerCommonItem("golem_iron","item");
    public static final RegistryObject<Item> GOLEM_OVER_ADV = registerCommonItem("golem_over_adv","item");
    public static final RegistryObject<Item> GOLEM_OVER_CORE = registerCommonItem("golem_over_core","item");
    public static final RegistryObject<Item> GOLEM_STONE = registerCommonItem("golem_stone","item");
    public static final RegistryObject<Item> GOLEM_STRAW = registerCommonItem("golem_straw","item");
    public static final RegistryObject<Item> GOLEM_TALLOW = registerCommonItem("golem_tallow","item");
    public static final RegistryObject<Item> GOLEM_THAUMIUM = registerCommonItem("golem_thaumium","item");
    public static final RegistryObject<Item> GOLEM_UPGRADE_AIR = registerCommonItem("golem_upgrade_air","item");
    public static final RegistryObject<Item> GOLEM_UPGRADE_EARTH = registerCommonItem("golem_upgrade_earth","item");
    public static final RegistryObject<Item> GOLEM_UPGRADE_EMPTY = registerCommonItem("golem_upgrade_empty","item");
    public static final RegistryObject<Item> GOLEM_UPGRADE_ENTROPY = registerCommonItem("golem_upgrade_entropy","item");
    public static final RegistryObject<Item> GOLEM_UPGRADE_FIRE = registerCommonItem("golem_upgrade_fire","item");
    public static final RegistryObject<Item> GOLEM_UPGRADE_ORDER = registerCommonItem("golem_upgrade_order","item");
    public static final RegistryObject<Item> GOLEM_UPGRADE_WATER = registerCommonItem("golem_upgrade_water","item");
    public static final RegistryObject<Item> GOLEM_WOOD = registerCommonItem("golem_wood","item");
    public static final RegistryObject<Item> GOLEMDECOARMOR = registerCommonItem("golemdecoarmor","item");
    public static final RegistryObject<Item> GOLEMDECOBOWTIE = registerCommonItem("golemdecobowtie","item");
    public static final RegistryObject<Item> GOLEMDECODART = registerCommonItem("golemdecodart","item");
    public static final RegistryObject<Item> GOLEMDECOFEZ = registerCommonItem("golemdecofez","item");
    public static final RegistryObject<Item> GOLEMDECOGLASSES = registerCommonItem("golemdecoglasses","item");
    public static final RegistryObject<Item> GOLEMDECOMACE = registerCommonItem("golemdecomace","item");
    public static final RegistryObject<Item> GOLEMDECOTOPHAT = registerCommonItem("golemdecotophat","item");
    public static final RegistryObject<Item> GOLEMDECOVISOR = registerCommonItem("golemdecovisor","item");
    public static final RegistryObject<Item> HOVERGIRDLE = registerCommonItem("hovergirdle","item");
    public static final RegistryObject<Item> HOVERHARNESS = registerCommonItem("hoverharness","item");
    public static final RegistryObject<Item> INKWELL = registerCommonItem("inkwell","item");
    public static final RegistryObject<Item> IRONBELL = registerCommonItem("ironbell","item");
    public static final RegistryObject<Item> KEYGOLD = registerCommonItem("keygold","item");
    public static final RegistryObject<Item> KEYIRON = registerCommonItem("keyiron","item");
    public static final RegistryObject<Item> KNOWLEDGEFRAGMENT = registerCommonItem("knowledgefragment","item");
    public static final RegistryObject<Item> LABEL = registerCommonItem("label","item");
    public static final RegistryObject<Item> LABEL_OVER = registerCommonItem("label_over","item");
    public static final RegistryObject<Item> LIGHTNINGRING = registerCommonItem("lightningring","item");
    public static final RegistryObject<Item> LIGHTNINGRINGV = registerCommonItem("lightningringv","item");
    public static final RegistryObject<Item> LOOTBAG = registerCommonItem("lootbag","item");
    public static final RegistryObject<Item> LOOTBAGRARE = registerCommonItem("lootbagrare","item");
    public static final RegistryObject<Item> LOOTBAGUNC = registerCommonItem("lootbagunc","item");
    public static final RegistryObject<Item> MANA_BEAN = registerCommonItem("mana_bean","item");
    public static final RegistryObject<Item> MIRRORFRAME = registerCommonItem("mirrorframe","item");
    public static final RegistryObject<Item> MIRRORFRAME2 = registerCommonItem("mirrorframe2","item");
    public static final RegistryObject<Item> MIRRORGLASS = registerCommonItem("mirrorglass","item");
    public static final RegistryObject<Item> MIRRORHAND = registerCommonItem("mirrorhand","item");
    public static final RegistryObject<Item> NITOR = registerCommonItem("nitor","item");
    public static final RegistryObject<Item> NUGGETBEEF = registerCommonItem("nuggetbeef","item");
    public static final RegistryObject<Item> NUGGETCHICKEN = registerCommonItem("nuggetchicken","item");
    public static final RegistryObject<Item> NUGGETCOPPER = registerCommonItem("nuggetcopper","item");
    //public static final RegistryObject<Item> NUGGETFISH = registerCommonItem("dust","item");
    public static final RegistryObject<Item> NUGGETIRON = registerCommonItem("nuggetiron","item");
    public static final RegistryObject<Item> NUGGETLEAD = registerCommonItem("nuggetlead","item");
    public static final RegistryObject<Item> NUGGETPORK = registerCommonItem("nuggetpork","item");
    public static final RegistryObject<Item> NUGGETQUICKSILVER = registerCommonItem("nuggetquicksilver","item");
    public static final RegistryObject<Item> NUGGETSILVER = registerCommonItem("nuggetsilver","item");
    public static final RegistryObject<Item> NUGGETTHAUMIUM = registerCommonItem("nuggetthaumium","item");
    public static final RegistryObject<Item> NUGGETTIN = registerCommonItem("nuggettin","item");
    public static final RegistryObject<Item> NUGGETVOID = registerCommonItem("nuggetvoid","item");
    public static final RegistryObject<Item> OB_PLACER = registerCommonItem("ob_placer","item");
    public static final RegistryObject<Item> PHIAL = registerCommonItem("phial","item");
    public static final RegistryObject<Item> PHIALOVERLAY = registerCommonItem("phialoverlay","item");
    public static final RegistryObject<Item> PRIMAL_CRUSHER = registerCommonItem("primal_crusher","item");
    public static final RegistryObject<Item> QUICKSILVER = registerCommonItem("quicksilver","item");
    public static final RegistryObject<Item> RESEARCHNOTES = registerCommonItem("researchnotes","item");
    public static final RegistryObject<Item> RESEARCHNOTESOVERLAY = registerCommonItem("researchnotesoverlay","item");
    public static final RegistryObject<Item> RESONATOR = registerCommonItem("resonator","item");
    public static final RegistryObject<Item> RUNIC_AMULET = registerCommonItem("runic_amulet","item");
    public static final RegistryObject<Item> RUNIC_AMULET_EMERGENCY = registerCommonItem("runic_amulet_emergency","item");
    public static final RegistryObject<Item> RUNIC_GIRDLE = registerCommonItem("runic_girdle","item");
    public static final RegistryObject<Item> RUNIC_GIRDLE_KINETIC = registerCommonItem("runic_girdle_kinetic","item");
    public static final RegistryObject<Item> RUNIC_RING = registerCommonItem("runic_ring","item");
    public static final RegistryObject<Item> RUNIC_RING_CHARGED = registerCommonItem("runic_ring_charged","item");
    public static final RegistryObject<Item> RUNIC_RING_LESSER = registerCommonItem("runic_ring_lesser","item");
    public static final RegistryObject<Item> RUNIC_RING_REGEN = registerCommonItem("runic_ring_regen","item");
    public static final RegistryObject<Item> SANITYCHECKER = registerCommonItem("sanitychecker","item");
    public static final RegistryObject<Item> SHARD = registerCommonItem("shard","item");
    public static final RegistryObject<Item> SHARD_BALANCED = registerCommonItem("shard_balanced","item");
    public static final RegistryObject<Item> SINISTER_STONE = registerCommonItem("sinister_stone","item");
    public static final RegistryObject<Item> SINISTER_STONE_ACTIVE = registerCommonItem("sinister_stone_active","item");
    public static final RegistryObject<Item> SOAP = registerCommonItem("soap","item");
    public static final RegistryObject<Item> STAFF_ROD_BLAZE = registerCommonItem("dust","item");
    public static final RegistryObject<Item> STAFF_ROD_BONE = registerCommonItem("dust","item");
    public static final RegistryObject<Item> STAFF_ROD_GREATWOOD = registerCommonItem("staff_rod_greatwood","item");
    public static final RegistryObject<Item> STAFF_ROD_ICE = registerCommonItem("staff_rod_ice","item");
    public static final RegistryObject<Item> STAFF_ROD_OBSIDIAN = registerCommonItem("staff_rod_obsidian","item");
    public static final RegistryObject<Item> STAFF_ROD_PRIMAL = registerCommonItem("staff_rod_primal","item");
    public static final RegistryObject<Item> STAFF_ROD_QUARTZ = registerCommonItem("staff_rod_quartz","item");
    public static final RegistryObject<Item> STAFF_ROD_REED = registerCommonItem("staff_rod_reed","item");
    public static final RegistryObject<Item> STAFF_ROD_SILVERWOOD = registerCommonItem("staff_rod_silverwood","item");
    public static final RegistryObject<Item> TAINT_SLIME = registerCommonItem("taint_slime","item");
    public static final RegistryObject<Item> TAINT_TENDRIL = registerCommonItem("taint_tendril","item");
    public static final RegistryObject<Item> TALLOW = registerCommonItem("tallow","item");
    public static final RegistryObject<Item> THAUMIUMAXE = registerCommonItem("thaumiumaxe","item");
    public static final RegistryObject<Item> THAUMIUMBOOTS = registerCommonItem("thaumiumboots","item");
    public static final RegistryObject<Item> THAUMIUMCHEST = registerCommonItem("dust","item");
    public static final RegistryObject<Item> THAUMIUMFORTRESSCHEST = registerCommonItem("thaumiumfortresschest","item");
    public static final RegistryObject<Item> THAUMIUMFORTRESSHELM = registerCommonItem("thaumiumfortresshelm","item");
    public static final RegistryObject<Item> THAUMIUMFORTRESSLEGS = registerCommonItem("thaumiumfortresslegs","item");
    public static final RegistryObject<Item> THAUMIUMHELM = registerCommonItem("thaumiumhelm","item");
    public static final RegistryObject<Item> THAUMIUMHOE = registerCommonItem("thaumiumhoe","item");
    public static final RegistryObject<Item> THAUMIUMINGOT = registerCommonItem("thaumiumingot","item");
    public static final RegistryObject<Item> THAUMIUMLEGS = registerCommonItem("thaumiumlegs","item");
    public static final RegistryObject<Item> THAUMIUMPICK = registerCommonItem("thaumiumpick","item");
    public static final RegistryObject<Item> THAUMIUMSHOVEL = registerCommonItem("thaumiumshovel","item");
    public static final RegistryObject<Item> THAUMIUMSWORD = registerCommonItem("thaumiumsword","item");
    public static final RegistryObject<Item> THAUMONOMICON = registerCommonItem("thaumonomicon","item");
    public static final RegistryObject<Item> THAUMONOMICONCHEAT = registerCommonItem("thaumonomiconcheat","item");
    public static final RegistryObject<Item> TRIPLETREAT = registerCommonItem("tripletreat","item");
    public static final RegistryObject<Item> VIS_AMULET = registerCommonItem("vis_amulet","item");
    public static final RegistryObject<Item> VIS_AMULET_LESSER = registerCommonItem("vis_amulet_lesser","item");
    public static final RegistryObject<Item> VOIDAXE = registerCommonItem("voidaxe","item");
    public static final RegistryObject<Item> VOIDBOOTS = registerCommonItem("dust","item");
    public static final RegistryObject<Item> VOIDCHEST = registerCommonItem("voidchest","item");
    public static final RegistryObject<Item> VOIDHELM = registerCommonItem("voidhelm","item");
    public static final RegistryObject<Item> VOIDHOE = registerCommonItem("voidhoe","item");
    public static final RegistryObject<Item> VOIDINGOT = registerCommonItem("voidingot","item");
    public static final RegistryObject<Item> VOIDLEGS = registerCommonItem("voidlegs","item");
    public static final RegistryObject<Item> VOIDPICK = registerCommonItem("voidpick","item");
    public static final RegistryObject<Item> VOIDROBECHEST = registerCommonItem("voidrobechest","item");
    public static final RegistryObject<Item> VOIDROBECHESTOVER = registerCommonItem("voidrobechestover","item");
    public static final RegistryObject<Item> VOIDROBEHELM = registerCommonItem("voidrobehelm","item");
    public static final RegistryObject<Item> VOIDROBELEGS = registerCommonItem("voidrobelegs","item");
    public static final RegistryObject<Item> VOIDROBELEGSOVER = registerCommonItem("voidrobelegsover","item");
    public static final RegistryObject<Item> VOIDSEED = registerCommonItem("voidseed","item");
    public static final RegistryObject<Item> VOIDSHOVEL = registerCommonItem("voidshovel","item");
    public static final RegistryObject<Item> VOIDSWORD = registerCommonItem("voidsword","item");
    public static final RegistryObject<Item> WAND_CAP_COPPER = registerCommonItem("wand_cap_copper","item");
    public static final RegistryObject<Item> WAND_CAP_GOLD = registerCommonItem("wand_cap_gold","item");
    public static final RegistryObject<Item> WAND_CAP_IRON = registerCommonItem("wand_cap_iron","item");
    public static final RegistryObject<Item> WAND_CAP_SILVER = registerCommonItem("dust","item");
    public static final RegistryObject<Item> WAND_CAP_SILVER_INERT = registerCommonItem("wand_cap_silver_inert","item");
    public static final RegistryObject<Item> WAND_CAP_THAUMIUM = registerCommonItem("wand_cap_thaumium","item");
    public static final RegistryObject<Item> WAND_CAP_THAUMIUM_INERT = registerCommonItem("wand_cap_thaumium_inert","item");
    public static final RegistryObject<Item> WAND_CAP_VOID = registerCommonItem("wand_cap_void","item");
    public static final RegistryObject<Item> WAND_CAP_VOID_INERT = registerCommonItem("wand_cap_void_inert","item");
    public static final RegistryObject<Item> WAND_ROD_BLAZE = registerCommonItem("wand_rod_blaze","item");
    public static final RegistryObject<Item> WAND_ROD_BONE = registerCommonItem("wand_rod_bone","item");
    public static final RegistryObject<Item> WAND_ROD_GREATWOOD = registerCommonItem("wand_rod_greatwood","item");
    public static final RegistryObject<Item> WAND_ROD_ICE = registerCommonItem("wand_rod_ice","item");
    public static final RegistryObject<Item> WAND_ROD_OBSIDIAN = registerCommonItem("wand_rod_obsidian","item");
    public static final RegistryObject<Item> WAND_ROD_QUARTZ = registerCommonItem("wand_rod_quartz","item");
    public static final RegistryObject<Item> WAND_ROD_REED = registerCommonItem("wand_rod_reed","item");
    public static final RegistryObject<Item> WAND_ROD_SILVERWOOD = registerCommonItem("wand_rod_silverwood","item");
    public static final RegistryObject<Item> WISPESSENCE = registerCommonItem("wispessence","item");
    public static final RegistryObject<Item> TESTWAND = registerWandItem("test_wand","item");
    private static RegistryObject<Item> registerStackOneItem(String name, String quality) {
        return register(name, () -> new ModItemGeneration(new Item.Properties().stacksTo(1), quality));
    }

    private static RegistryObject<Item> registerCommonItem(String name, String quality) {
        return register(name, () -> new ModItemGeneration(new Item.Properties(), quality));
    }
    private static RegistryObject<Item> registerWandItem(String name, String quality) {
        return register(name, () -> new Wand(new Item.Properties().stacksTo(1), quality));
    }

    private static <T extends Item> RegistryObject<T> register(String name, Supplier<T> itemSup) {
        return ITEMS.register(name, itemSup);
    }
}
